name: Build

on:
  workflow_dispatch:
    inputs:
      Env:
        required: true
        default: 'SIT'
        type: choice
        options: ['SIT', 'UAT', 'PROD']
      DeployOrFallback:
        type: choice
        options: ['DP', 'FB']
jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Build
        run: |
          echo "Building code"
          echo "::set-output name=build_result::success"
