name: Build

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ha-linux
    steps:
      - name: Build
        run: |
          echo "Building code"
          echo "::set-output name=build_result::success"
