name: Build

on:
  workflow_dispatch:
    inputs:
      auth_file:
        required: true
        default: 'SIT'
        type: choice
        options: ['SIT', 'UAT', 'PROD']
      pvc_path:
        type: string
jobs:
  build:
    runs-on: [ha-linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          ls
