# This is a basic workflow to help you get started with Actions

name: cms_deploy

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      Env:
        options: ['SIT', 'UAT', 'PROD']
      Deploy/Fallback:
        options: ['DP', 'FB']
    secrets:
      CMS_MYSQL_DRIVER:
        required: true
      CMS_MYSQL_PASSWORD:
        required: true
      CMS_MYSQL_URL:
        required: true
      CMS_MYSQL_USERNAME:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: xudongk/testMybatis
      - name: deploy
        uses: xudongk/testMybatis/.github/actions/migation@main
        with:
          json: 11
          CMS_MYSQL_DRIVER: ${{ secrets.CMS_MYSQL_DRIVER}}
          CMS_MYSQL_PASSWORD: ${{ secrets.CMS_MYSQL_PASSWORD}}
          CMS_MYSQL_URL: ${{ secrets.CMS_MYSQL_URL}}
          CMS_MYSQL_USERNAME: ${{ secrets.CMS_MYSQL_USERNAME}}
  
      
      


