# This is a basic workflow to help you get started with Actions

name: cms_deploy

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      Env:
        required: true
        default: 'SIT'
        type: choice
        options: ['SIT', 'UAT', 'PROD']
      DeployOrFallback:
        type: choice
        options: ['DP', 'FB']
    secrets:
      SIT_MYSQL_DRIVER:
        required: true
      SIT_MYSQL_PASSWORD:
        required: true
      SIT_MYSQL_URL:
        required: true
      SIT_MYSQL_USERNAME:
        required: true
      UAT_MYSQL_DRIVER:
        required: true
      UAT_MYSQL_PASSWORD:
        required: true
      UAT_MYSQL_URL:
        required: true
      UAT_MYSQL_USERNAME:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy SIT
        if: ${{ inputs.Env == 'SIT' }}
        uses: xudongk/testMybatis/.github/actions/test@main
        with:
          Env: ${{ inputs.Env }}
          DeployType: ${{ inputs.DeployOrFallback }}
          DRIVER: ${{ secrets.SIT_MYSQL_DRIVER }}
          PASSWORD: ${{ secrets.SIT_MYSQL_PASSWORD }}
          URL: ${{ secrets.SIT_MYSQL_URL }}
          USERNAME: ${{ secrets.SIT_MYSQL_USERNAME }}
      - name: Deploy UAT
        if: ${{ inputs.Env == 'UAT' }}
        uses: xudongk/testMybatis/.github/actions/test@main
        with:
          Env: ${{ inputs.Env }}
          DeployType: ${{ inputs.DeployOrFallback }}
          DRIVER: ${{ secrets.UAT_MYSQL_DRIVER }}
          PASSWORD: ${{ secrets.UAT_MYSQL_PASSWORD }}
          URL: ${{ secrets.UAT_MYSQL_URL }}
          USERNAME: ${{ secrets.UAT_MYSQL_USERNAME }}
