# This is a basic workflow to help you get started with Actions

name: cms_deploy

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      json:
        type: string

jobs:
  getCode:
    name: clone
    uses: xudongk/testMybatis/.github/workflows/Testenv2.yml@main
    with:
      json: 11
    secrets:
      CMS_MYSQL_DRIVER: ${{ secrets.CMS_MYSQL_DRIVER}}
      CMS_MYSQL_PASSWORD: ${{ secrets.CMS_MYSQL_PASSWORD}}
      CMS_MYSQL_URL: ${{ secrets.CMS_MYSQL_URL}}
      CMS_MYSQL_USERNAME: ${{ secrets.CMS_MYSQL_USERNAME}}
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: xudongk/testMybatis
          token: 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
      
      


