# This is a basic workflow to help you get started with Actions

name: cms_deploy

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      Env:
        required: true
        default: 'SIT'
        type: choice
        options: ['SIT', 'UAT', 'PROD']
      DeployOrFallback:
        type: choice
        options: ['DP', 'FB']
    secrets:
      CMS_MYSQL_DRIVER:
        required: true
      CMS_MYSQL_PASSWORD:
        required: true
      CMS_MYSQL_URL:
        required: true
      CMS_MYSQL_USERNAME:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: xudongk/testMybatis/.github/actions/migation@main
        with:
          Env: ${{ inputs.Env }}
          DeployType: ${{ inputs.DeployOrFallback }}
          CMS_MYSQL_DRIVER: ${{ secrets.CMS_MYSQL_DRIVER}}
          CMS_MYSQL_PASSWORD: ${{ secrets.CMS_MYSQL_PASSWORD}}
          CMS_MYSQL_URL: ${{ secrets.CMS_MYSQL_URL}}
          CMS_MYSQL_USERNAME: ${{ secrets.CMS_MYSQL_USERNAME}}
