name: pvc test

on:
  workflow_dispatch:
    inputs:
      pod_name:
        type: string
      auth_file:
        required: true
        default: 'SIT'
        type: choice
        options: ['SIT', 'UAT', 'PROD']
      pvc_path:
        type: string
jobs:
  pvc:
    runs-on: [ha-linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: copy file
        run: |
          cd file
          kubectl cp 1.txt my-pvc-pod-798df58966-dtghl:/
