name: Sync Repositories

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          path: source

      - name: Set up Git for destination repository
        run: |
          mkdir destination
          cd destination
          git clone  https://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@github.com/xudongk/testPush.git
          cd testPush
          rm -rf *

      - name: Copy files from source to destination
        run: |
          pwd
          ls
          cp -r source/* destination/testPush/
      - name: Commit and push changes to destination repository
        run: |
          cd destination/testPush
          git config --global user.email "xudongkej@163.com"
          git config --global user.name "xudongk"
          git add .
          git commit -m "Sync from source repository"
          git push https://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@github.com/xudongk/testPush.git

