name: Sync Repositories

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          path: source

      - name: Set up Git for destination repository
        run: |
          mkdir destination
          cd destination
          git init
          git config --global init.defaultBranch main
          git remote set-url testPush https://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@github.com/xudongk/testPush.git
          git pull testPush main
      - name: Checkout destination repository
        run: |
          git clone https://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@github.com/xudongk/testPush.git destination
          cd destination
          rm -rf *
      - name: Copy files from source to destination
        run: |
          pwd
          cp -r source/* destination/
          cd destination
          ls
          pwd
      - name: Commit and push changes to destination repository
        run: |
          cd destination
          git add
          git commit -m "Sync from source repository"
          git push
