name: Sync Repositories

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          path: source

      - name: Set up Git for destination repository
        run: |
          mkdir destination
          cd destination
          git clone https://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@github.com/xudongk/testPush.git
          ls
          cd testPush
          rm -rf *
      - name: Copy files from source to destination
        run: |
          pwd
          ls
          cp -r source/* destination/
          cd destination
          ls
          pwd
      - name: Commit and push changes to destination repository
        run: |
          cd destination/testPush
          git add .
          git config user.email "xudongkej@163.com"
          git config user.name "xudongk"
          git commit -m "Sync from source repository"
          export GITHUB_TOKEN=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
          git push https://xudongk@github.com/xudongk/testPush.git