name: Sync Repositories

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          path: source

      - name: Set up Git for destination repository
        run: |
          mkdir destination
          cd destination
          git clone https://xudongk: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@github.com/xudongk/testPush.git
          cd testPush
          rm -rf *

      - name: Copy files from source to destination
        run: |
          pwd
          ls
          cp -r source/* destination/testPush/
      - name: Commit and push changes to destination repository
        run: |
          cd destination/testPush
          git config --global user.email "xudongkej@163.com"
          git config --global user.name "xudongk"
          git remote add origin https://github.com/xudongk/testPush.git
          git remote set-url origin https://xudongk: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@github.com/xudongk/testPush.git
          git add .
          git commit -m "Sync from source repository"
          git push https://xudongk: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@github.com/xudongk/testPush.git

