name: push code
on:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          path: source
      - name: Set up Git for destination repository
        run: |
          mkdir destination
          cd destination
          git clone  https://x-access-token:${{secrets.GIT_TOKEN}}@github.com/xudongk/testPush.git
          cd testPush
          rm -rf *

      - name: Copy files from source to destination
        run: |
          pwd
          ls
          cp -r source/* destination/testPush/
      - name: Commit and push changes to destination repository
        run: |
          cd destination/testPush
          git config --global http.sslVerify "false"
          git config --global user.email "xudongkej@163.com"
          git config --global user.name "xudongk"
          git add .
          git commit -m "Sync from source repository"
          git push

